name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # cần để tạo release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore WinFormsApp1.csproj

      - name: Publish single-file exe
        run: dotnet publish WinFormsApp1.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish/AppDownloadVideo.exe   # chỉ upload file exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/AppDownloadVideo.exe   # chỉ attach exe
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
